### ISSUE TITLE
User Feedback Page

### ISSUE THREAD

**Issue by hassan-yaqoob** [GroupProjectSem3/Haley#69]

**Comment by GeetAgar** [comment]
Added initial forms on the slack
link
website feedback -https://app.mopinion.com/survey/public/take-survey/029fcd504375bcb4f39a5c493a5ccc83ecf4078f
Diagnosis feedback-  https://app.mopinion.com/survey/public/take-survey/7f379c2ed347e2977420c2163a18902ebda045cb
